### ISSUE TITLE
v1.8.1 Strips quotes from multiple variables in project.pbxproj

### ISSUE THREAD

**Issue by tmac24utm** [alexandermendes/semantic-release-react-native#5]
The fix for issue #4  has stripped quotes from other variables (not just CURRENT_PROJECT_VERSION & MARKETING_VERSION).

I think it's due to the regex (tested using https://regexr.com/);

**Old:**
`(['CURRENT_PROJECT_VERSION'|'MARKETING_VERSION']) = "(.*)"`
![Screenshot 2023-08-08 at 10 46 29](https://github.com/alexandermendes/semantic-release-react-native/assets/17890684/8a6f600a-1f0b-426e-ad9d-1db2784f621f)

**(Proposed) New:**
`(CURRENT_PROJECT_VERSION|MARKETING_VERSION) = "(.*)"`
![Screenshot 2023-08-08 at 10 45 22](https://github.com/alexandermendes/semantic-release-react-native/assets/17890684/34f58217-cc4a-449d-89ac-440f619d8af9)

In the code a string variable is referenced for the regex, not sure there's a good way to include the quotes so would be best being stripped out first (imo): `.replace(/'([^']*)'/g)`

**Comment by rofe** [comment]
@alexandermendes I also had to downgrade to v1.8.0 again, as v1.8.1 removes too many quotes. See [here](https://github.com/adobe/helix-sidekick-extension/commit/f86b2b8de314940ef2b7ccded789054be3a13d87#diff-ca261baf0238c236f2d8ddf8a5314a2b97fd7dedb663256e4545b708a01432f9) for an example of a commit which makes the `.pbxproj` file unreadable for XCode.

**Comment by alexandermendes** [comment]
Ok refined that pattern a bit, should hopefully be better with [v1.8.2](https://github.com/alexandermendes/semantic-release-react-native/releases/tag/v1.8.2) 🤞
